version: "3"
services:
  eureka:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/eureka-server:latest
    environment:
      - APPLICATION_NAME=demo-eureka-server
      - SECURITY_USERNAME=admin
      - SECURITY_PASSWORD=admin
      - SERVICE_URL='http://${SECURITY_USERNAME}:${SECURITY_PASSWORD}@localhost:8761/eureka/'
    ports:
      - "8761:8761"